In [18]:
# TensorFlow and tf.keras
import tensorflow as tf
import numpy as np
from tensorflow import keras

#tf version should be 2.2 or higher
tf.__version__

'2.13.0'

In [19]:
#get data
(train_images, train_labels), (test_images, test_labels) = \
      keras.datasets.mnist.load_data()

In [20]:
#scale model
train_images = train_images / 255.0
test_images = test_images / 255.0

In [21]:
#setup model
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(10, activation = tf.nn.softmax)
])

In [22]:
#compile model
model.compile(optimizer='sgd',
          loss='sparse_categorical_crossentropy',
          metrics=['accuracy'])

In [23]:
#train model
#model will be trained on 1875 batches of 32 images each; 1875*32 = 60000 images
#The default batch size in model.fit is 32
model.fit(train_images, train_labels, epochs=50)

Epoch 1/50
1875/1875 [==============================] - 1s 621us/step - loss: 0.7727 - accuracy: 0.8171
Epoch 2/50
1875/1875 [==============================] - 1s 617us/step - loss: 0.4560 - accuracy: 0.8808
Epoch 3/50
1875/1875 [==============================] - 1s 614us/step - loss: 0.4034 - accuracy: 0.8914
Epoch 4/50
1875/1875 [==============================] - 1s 632us/step - loss: 0.3769 - accuracy: 0.8967
Epoch 5/50
1875/1875 [==============================] - 1s 637us/step - loss: 0.3600 - accuracy: 0.9006
Epoch 6/50
1875/1875 [==============================] - 1s 642us/step - loss: 0.3482 - accuracy: 0.9039
Epoch 7/50
1875/1875 [==============================] - 1s 717us/step - loss: 0.3392 - accuracy: 0.9054
Epoch 8/50
1875/1875 [==============================] - 1s 635us/step - loss: 0.3320 - accuracy: 0.9078
Epoch 9/50
1875/1875 [==============================] - 1s 631us/step - loss: 0.3262 - accuracy: 0.9088
Epoch 10/50
1875/1875 [==============================] - 1s 631u

In [24]:
#evaluate
test_loss, test_acc = model.evaluate(test_images,  test_labels)
print('\nTest accuracy:', test_acc)

313/313 [==============================] - 0s 607us/step - loss: 0.2727 - accuracy: 0.9235

Test accuracy: 0.9235000014305115


In [25]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:10])

1/1 [==============================] - 0s 25ms/step


In [26]:
#Raw predictions
predictions

array([[3.5850942e-05, 2.4016378e-09, 1.4538353e-04, 4.2583984e-03,
        1.2495250e-06, 3.1581465e-05, 4.9010889e-09, 9.9514008e-01,
        2.4749954e-05, 3.6278789e-04],
       [2.0730048e-03, 7.0565216e-06, 9.7129637e-01, 3.4495890e-03,
        9.5618367e-11, 8.5884677e-03, 1.2980832e-02, 1.8365177e-12,
        1.6045315e-03, 2.2074638e-09],
       [4.3561558e-06, 9.7191846e-01, 1.4889522e-02, 2.9986526e-03,
        1.6349067e-04, 1.5299196e-03, 1.5405227e-03, 3.5133762e-03,
        3.0690348e-03, 3.7258648e-04],
       [9.9963403e-01, 4.0763937e-11, 1.0730594e-04, 6.0189586e-06,
        1.9136813e-08, 1.2277522e-04, 9.0750662e-05, 1.1551558e-05,
        1.8808145e-05, 8.7737417e-06],
       [3.9974679e-04, 1.2313155e-06, 3.9578481e-03, 6.9017864e-05,
        9.6379507e-01, 3.4714610e-04, 2.4575705e-03, 4.9257576e-03,
        3.2889692e-03, 2.0757739e-02],
       [3.7104076e-07, 9.8718864e-01, 3.1256841e-03, 2.3832961e-03,
        2.6620697e-05, 1.0607373e-04, 3.7545928e-05, 3.82

In [27]:
# Print our model's predictions
print(np.argmax(predictions, axis=1))

[7 2 1 0 4 1 4 9 6 9]


In [28]:
# Check our predictions against the ground truths
print(test_labels[:10]) # [7, 2, 1, 0, 4]

[7 2 1 0 4 1 4 9 5 9]
